export const CHANGE_PLAYER = 'CHANGE_PLAYER';
export const SET_SQUARES = 'SET_SQUARES';
export const TOGGLE_FILTER_MODAL = 'OPEN_FILTER_MODAL';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const CREATE_INVOICE = 'CREATE_INVOICE';
